#!/bin/sh

#$NOMBRE_SERVICIO $ARTIFACT_LOCATION $RUTAREPOGIT $BRANCHGIT $RUTABASERECETARIO $HOME


NOMBRE_SERVICIO=$1
ARTIFACT_LOCATION=$2

RUTAREPOGIT=$3 #https://github.com/caferrerb/domotica.git
BRANCHGIT=$4 #master
RUTABASERECETARIO=$5 #infraestrutura/recetas
HOME=$6 #/Users/caferrerb/Desktop/folder
RUTACOMPLETAGIT=$HOME/$RUTABASERECETARIO

RUTABASE=$HOME/$NOMBRE_SERVICIO
RUTALOGS=$RUTABASE/logs
RUTABIN=$RUTABASE/bin


echo "parametros:"
echo NOMBRE_SERVICIO $1
echo ARTIFACT_LOCATION $2
echo RUTAREPOGIT $3
echo BRANCHGIT $4
echo RUTABASERECETARIO $5
echo HOME $6

echo "RUTABASE=" $RUTABASE
echo "RUTALOGS=" $RUTALOGS
echo "RUTABIN=" $RUTABIN
echo "RUTACOMPLETAGIT=" $RUTACOMPLETAGIT


rm -rf $RUTABASE


cd $HOME

git init 
git config core.sparseCheckout true
git remote add -f origin $RUTAREPOGIT 
echo $RUTABASERECETARIO"/"$NOMBRE_SERVICIO"/*" > .git/info/sparse-checkout
git checkout $BRANCHGIT 

cp  -r $RUTACOMPLETAGIT/$NOMBRE_SERVICIO $HOME
rm -rf $RUTACOMPLETAGIT
rm -rf $HOME/.git
rm -rf $HOME/infraestrutura

cd $RUTABASE
ls -l
sh configdeploy.sh $NOMBRE_SERVICIO $ARTIFACT_LOCATION $HOME

