#!/bin/sh

NOMBRE_SERVICIO=$1
ARTIFACT_LOCATION=$2

HOME=$3 #/Users/caferrerb/Desktop/folder

RUTABASE=$HOME/$NOMBRE_SERVICIO
RUTALOGS=$RUTABASE/logs
RUTABIN=$RUTABASE/bin


cd $RUTABIN
wget -O $NOMBRE_SERVICIO.jar $ARTIFACT_LOCATION

sh runservice.sh